################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Src/HAL/STM32F4xx_HAL_Driver/Src \
Src/Middleware/FATFS \
Src/Middleware/FreeRTOS-Kernel \
Src/Middleware/SEGGER/SystemView/SEGGER \
Src/Middleware/SEGGER/SystemView/Sample/FreeRTOS/Config \
Src/Middleware/SEGGER/SystemView/Sample/FreeRTOS \
Src/Middleware/lvgl/src/core \
Src/Middleware/lvgl/src/draw/arm2d \
Src/Middleware/lvgl/src/draw/gd32_ipa \
Src/Middleware/lvgl/src/draw \
Src/Middleware/lvgl/src/draw/nxp \
Src/Middleware/lvgl/src/draw/nxp/pxp \
Src/Middleware/lvgl/src/draw/nxp/vglite \
Src/Middleware/lvgl/src/draw/sdl \
Src/Middleware/lvgl/src/draw/stm32_dma2d \
Src/Middleware/lvgl/src/draw/sw \
Src/Middleware/lvgl/src/draw/swm341_dma2d \
Src/Middleware/lvgl/src/font \
Src/Middleware/lvgl/src/hal \
Src/Middleware/lvgl/src/layouts/flex \
Src/Middleware/lvgl/src/layouts/grid \
Src/Middleware/lvgl/src/libs/bmp \
Src/Middleware/lvgl/src/libs/ffmpeg \
Src/Middleware/lvgl/src/libs/freetype \
Src/Middleware/lvgl/src/libs/fsdrv \
Src/Middleware/lvgl/src/libs/gif \
Src/Middleware/lvgl/src/libs/png \
Src/Middleware/lvgl/src/libs/qrcode \
Src/Middleware/lvgl/src/libs/rlottie \
Src/Middleware/lvgl/src/libs/sjpg \
Src/Middleware/lvgl/src/libs/tiny_ttf \
Src/Middleware/lvgl/src/misc \
Src/Middleware/lvgl/src/others/file_explorer \
Src/Middleware/lvgl/src/others/fragment \
Src/Middleware/lvgl/src/others/gridnav \
Src/Middleware/lvgl/src/others/ime \
Src/Middleware/lvgl/src/others/imgfont \
Src/Middleware/lvgl/src/others/monkey \
Src/Middleware/lvgl/src/others/msg \
Src/Middleware/lvgl/src/others/snapshot \
Src/Middleware/lvgl/src/themes/basic \
Src/Middleware/lvgl/src/themes/default \
Src/Middleware/lvgl/src/themes/mono \
Src/Middleware/lvgl/src/widgets/animimg \
Src/Middleware/lvgl/src/widgets/arc \
Src/Middleware/lvgl/src/widgets/bar \
Src/Middleware/lvgl/src/widgets/btn \
Src/Middleware/lvgl/src/widgets/btnmatrix \
Src/Middleware/lvgl/src/widgets/calendar \
Src/Middleware/lvgl/src/widgets/canvas \
Src/Middleware/lvgl/src/widgets/chart \
Src/Middleware/lvgl/src/widgets/checkbox \
Src/Middleware/lvgl/src/widgets/colorwheel \
Src/Middleware/lvgl/src/widgets/dropdown \
Src/Middleware/lvgl/src/widgets/img \
Src/Middleware/lvgl/src/widgets/imgbtn \
Src/Middleware/lvgl/src/widgets/keyboard \
Src/Middleware/lvgl/src/widgets/label \
Src/Middleware/lvgl/src/widgets/led \
Src/Middleware/lvgl/src/widgets/line \
Src/Middleware/lvgl/src/widgets/list \
Src/Middleware/lvgl/src/widgets/menu \
Src/Middleware/lvgl/src/widgets/meter \
Src/Middleware/lvgl/src/widgets/msgbox \
Src/Middleware/lvgl/src/widgets/objx_templ \
Src/Middleware/lvgl/src/widgets/roller \
Src/Middleware/lvgl/src/widgets/slider \
Src/Middleware/lvgl/src/widgets/span \
Src/Middleware/lvgl/src/widgets/spinbox \
Src/Middleware/lvgl/src/widgets/spinner \
Src/Middleware/lvgl/src/widgets/switch \
Src/Middleware/lvgl/src/widgets/table \
Src/Middleware/lvgl/src/widgets/tabview \
Src/Middleware/lvgl/src/widgets/textarea \
Src/Middleware/lvgl/src/widgets/tileview \
Src/Middleware/lvgl/src/widgets/win \
Src \
Src/core \
Startup \

